### ISSUE TITLE
Enable teachers to update

### ISSUE THREAD

**Issue by rhulucas** [rhulucas/hello1#1]
**User story**
As a. teacher, I tend to lose my paper records.So, I want to update the grades online so that the grades will be stored even if I lose the paper records.

*persona: teacher who tend to lose paper records
*feature: teacher updates the grades online
*business value: the grades will be stored even if the paper records are lost

**Task List**

- [x] Make sure the data base schemes handle grade update
- [ ] Create HTML view for updating grades
- [ ] Connect the HTML view the database/backend to finish the function ...

**Acceptance Criteria**
1.only for the current semester
2.works only for Chrome

**Acceptance Tests**
1.the teacher should able to update existing grades for students in the course
2.the teacher should be able to remove existing grades for students in the course
3.the teacher should be able to add new grades for students
